### ISSUE TITLE
Nuxt Build is taking a long time

### ISSUE THREAD

**Issue by francescobm** [nuxt-community/express-template#76]
Hi, 
I'm experiencing some problems when launching my nuxt app on AWS EC2. When I run `nuxt build` the build takes about 5 minutes before being completed. In local it takes about 40 secs. 

The build run quite fast until it reach 91%, then it stalls for a long time before completing.
I am launching Nuxt programmatically, with expressjs.

Does anyone experienced a similar issue ?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/express-template/issues/c58">#c58</a>)</em></sub></div>

**Comment by logaretm** [comment]
Well from my own trials, nuxt seems to take a lot of resources when building, depending on your app size. often the build process got killed because it tried to consume a lot of resources. this happened on t2.nano and t2.micro instances. I have 3 apps that need to be run together. and yes, more often than not the process gets stuck on 91%

Any instance with more than 1GB seems to work fine for me, however we switched the entire workflow, we now use docker with elasticbeanstalk. The containers are being bundled with the built files before being deployed which saves us the trouble of upgrading the t2 instances.

**Comment by francescobm** [comment]
Hi @logaretm,
thanks for your feedback, as a temporary solution I am pulling my code already compiled into my EC2 instance. However, is not a very elegant solution. I will definitively look into docker and Elastic Beanstalk. 
Thanks and best of luck with your project !
